"""Initial migration

Revision ID: c6af8897ef17
Revises: 
Create Date: 2025-06-07 23:39:27.698689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6af8897ef17'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disaster',
    sa.Column('disaster_id', sa.Integer(), nullable=False),
    sa.Column('disaster_type', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('severity', sa.Float(), nullable=False),
    sa.Column('time_occurred', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('disaster_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('alert',
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('disaster_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=100), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('time_sent', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['disaster_id'], ['disaster.disaster_id'], ),
    sa.PrimaryKeyConstraint('alert_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert')
    op.drop_table('user')
    op.drop_table('disaster')
    # ### end Alembic commands ###
